name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: application-build
          path: build # 

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    environment: 
      name: testing
      url: ${{ steps.deploy.outputs.deployment-url }}
    steps:
      - uses: actions/checkout@v2
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: application-build
          path: build # O mesmo caminho usado para upload

      - name: Deploy to testing environment
        run: ./deploy-script.sh 

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Send failure notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: CI/CD Pipeline Failure
          to: developer@example.com
          body: The CI/CD pipeline failed. Please check the logs.
