name: CI/CD Pipeline

permissions:
  contents: write

on:
  push:
    branches:
      - master 

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test
      - name: Build application
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: application-build
          path: dist

  create_release:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false
          body: |
            Release notes for version 1.0.0.
      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/index.html
          asset_name: index.html
          asset_content_type: text/html

  deploy:
    needs: create_release
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v2
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: application-build
          path: dist
      - name: Deploy to testing environment
        run: ./deploy-script.sh

  notify:
    needs: [build_and_test, create_release, deploy]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Send failure notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: CI/CD Pipeline Failure
          to: developer@example.com
          body: The CI/CD pipeline failed. Please check the logs.
